import { generateOpenApiDocument } from "@formos/api";

/**
 * Serves the OpenAPI document for the Scalar docs page at /docs.
 * This is the ONLY non-tRPC route that exposes business info, and it is
 * explicitly allowed by the brief (docs/OpenAPI for Scalar). The document is
 * generated by introspecting the live tRPC router, so it never duplicates or
 * re-implements any business logic.
 */
export function GET() {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? "";
  const document = generateOpenApiDocument({
    baseUrl,
    title: "FormOS API",
    version: "0.1.0",
  });
  return Response.json(document);
}
