import { zodToJsonSchema } from "zod-to-json-schema";
import { appRouter } from "./root";

/**
 * Build an OpenAPI 3.1 document by INTROSPECTING the live tRPC router and its
 * Zod input schemas. We do not generate a parallel REST API — these operations
 * describe how the real tRPC procedures are reached over HTTP:
 *
 *   - queries:   GET  /api/trpc/<procedure>?input=<url-encoded JSON>
 *   - mutations: POST /api/trpc/<procedure>   (input as the JSON body)
 *
 * Because the doc is derived from the router itself, it can never drift away
 * from the procedures it documents.
 */

export interface OpenApiDocOptions {
  baseUrl?: string;
  title?: string;
  version?: string;
}

interface AnyProcedure {
  _def?: {
    type?: "query" | "mutation" | "subscription";
    inputs?: unknown[];
    meta?: {
      openapi?: { summary?: string; description?: string; tags?: string[] };
    };
  };
}

function isZodSchema(value: unknown): boolean {
  return (
    !!value &&
    typeof value === "object" &&
    typeof (value as { safeParse?: unknown }).safeParse === "function"
  );
}

export function generateOpenApiDocument(opts: OpenApiDocOptions = {}) {
  const baseUrl = opts.baseUrl ?? "";
  const title = opts.title ?? "FormOS API";
  const version = opts.version ?? "0.1.0";

  const procedures = (appRouter as unknown as { _def: { procedures: Record<string, AnyProcedure> } })
    ._def.procedures;

  const paths: Record<string, Record<string, unknown>> = {};
  const tagSet = new Set<string>();

  for (const [path, proc] of Object.entries(procedures)) {
    const def = proc._def ?? {};
    const type = def.type ?? "query";
    if (type === "subscription") continue;

    const meta = def.meta?.openapi ?? {};
    const tags = meta.tags ?? [path.split(".")[0] ?? "rpc"];
    tags.forEach((t) => tagSet.add(t));

    // The last .input() carries the effective schema for our procedures.
    const inputs = Array.isArray(def.inputs) ? def.inputs : [];
    const inputSchema = inputs[inputs.length - 1];
    let inputJsonSchema: Record<string, unknown> | undefined;
    if (isZodSchema(inputSchema)) {
      try {
        inputJsonSchema = zodToJsonSchema(inputSchema as never, {
          target: "openApi3",
          $refStrategy: "none",
        }) as Record<string, unknown>;
      } catch {
        inputJsonSchema = undefined;
      }
    }

    const url = `/api/trpc/${path}`;
    const httpMethod = type === "query" ? "get" : "post";
    const required = Array.isArray(
      (inputJsonSchema as { required?: unknown[] } | undefined)?.required,
    )
      ? ((inputJsonSchema as { required: unknown[] }).required.length > 0)
      : false;

    const envelopeNote =
      "Response uses the tRPC envelope `{ result: { data: <output> } }`. tRPC clients may also batch calls with `?batch=1`.";

    const operation: Record<string, unknown> = {
      operationId: path.replace(/\./g, "_"),
      summary: meta.summary ?? path,
      description: [meta.description, envelopeNote].filter(Boolean).join("\n\n"),
      tags,
      responses: {
        "200": {
          description: "Successful tRPC response.",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  result: {
                    type: "object",
                    properties: {
                      data: { description: "Procedure-specific output payload." },
                    },
                  },
                },
              },
            },
          },
        },
        default: { description: "tRPC error envelope." },
      },
    };

    if (type === "query") {
      operation.parameters = inputJsonSchema
        ? [
            {
              name: "input",
              in: "query",
              required,
              description:
                "URL-encoded JSON matching the procedure's input schema.",
              content: { "application/json": { schema: inputJsonSchema } },
            },
          ]
        : [];
    } else if (inputJsonSchema) {
      operation.requestBody = {
        required: true,
        content: { "application/json": { schema: inputJsonSchema } },
      };
    }

    paths[url] = { ...(paths[url] ?? {}), [httpMethod]: operation };
  }

  return {
    openapi: "3.1.0",
    info: {
      title,
      version,
      description:
        "OpenAPI description of the FormOS tRPC procedures.\n\n" +
        "All business logic is implemented as tRPC procedures — there is no separate REST API. " +
        "This document is generated by introspecting the live tRPC router and its Zod input " +
        "schemas, so it always stays aligned with the real procedures. Queries are reachable via " +
        "`GET /api/trpc/<procedure>?input=<json>` and mutations via `POST /api/trpc/<procedure>` " +
        "with the input as the JSON body.\n\n" +
        "Auth: management & analytics procedures (form.list/byId/create/update/publish/unpublish/remove, " +
        "analytics.*) require an admin passcode sent as the `x-admin-token` header. The public procedures " +
        "(form.bySlug, view.track, submission.create) are open for anonymous form-filling.",
    },
    servers: [{ url: baseUrl || "/" }],
    tags: Array.from(tagSet)
      .sort()
      .map((name) => ({ name })),
    paths,
  };
}

export type OpenApiDocument = ReturnType<typeof generateOpenApiDocument>;
